apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'maven-publish'

group = 'expo.modules.acpcore'
version = '0.1.0'

def expoModulesCorePlugin = new File(
  ["node", "--print", "require.resolve('expo-modules-core/package.json')"]
    .execute(null, rootDir)
    .text
    .trim()
).getParentFile().absolutePath + "/android/ExpoModulesCorePlugin.gradle"
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace "expo.modules.acpcore"
  compileSdkVersion safeExtGet("compileSdkVersion", 35)

  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 24)
    targetSdkVersion safeExtGet("targetSdkVersion", 35)
  }

  sourceSets {
    main {
      jniLibs.srcDirs = ["src/main/jniLibs"]
    }
  }

  publishing {
    singleVariant("release") {
      withSourcesJar()
    }
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${safeExtGet('kotlinVersion', '2.0.21')}"
  implementation "net.java.dev.jna:jna:5.14.0@aar"
}
