from pathlib import Path
import json
import re
import tomllib


REQUIREMENTS_IN_PATH = Path("requirements.in")
REQUIREMENTS_TXT_PATH = Path("requirements.txt")
PYPROJECT_PATH = Path("pyproject.toml")
BACKEND_CI_PATH = Path(".github/workflows/backend-ci.yml")
RELEASE_WORKFLOW_PATH = Path(".github/workflows/release.yml")
DEP_REVIEW_WORKFLOW_PATH = Path(".github/workflows/dependency-review.yml")
FRONTEND_CI_PATH = Path(".github/workflows/frontend-ci.yml")
DOCKERFILE_PATH = Path("Dockerfile")
ANCAP_MOBILE_PACKAGE_PATH = Path("ancap-mobile/package.json")
ANCAP_MOBILE_WORKSPACE_MANIFESTS = [
    Path("ancap-mobile/apps/acp-wallet/package.json"),
    Path("ancap-mobile/apps/acp-wallet-expo/package.json"),
    Path("ancap-mobile/packages/acp-api-client/package.json"),
    Path("ancap-mobile/packages/acp-bridge-client/package.json"),
    Path("ancap-mobile/packages/acp-bsc-client/package.json"),
    Path("ancap-mobile/packages/acp-wallet-sdk/package.json"),
]


_REQUIREMENT_OPERATOR_PATTERN = re.compile(r"\s*(?:===|==|~=|!=|<=|>=|<|>)")
_EXACT_PIN_PATTERN = re.compile(r"(?<![=<>!~])==(?![=])")


def _iter_requirement_lines(text: str):
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or line.startswith("--hash="):
            continue
        yield line


def _requirement_name(requirement: str) -> str:
    base = _REQUIREMENT_OPERATOR_PATTERN.split(requirement.strip(), maxsplit=1)[0]
    return base.split("[", 1)[0].strip()


def _requirement_names(text: str) -> set[str]:
    return {_requirement_name(line) for line in _iter_requirement_lines(text)}


def _is_exact_pin(requirement: str) -> bool:
    return _EXACT_PIN_PATTERN.search(requirement) is not None


def _has_exact_pin(text: str, package_name: str) -> bool:
    for line in _iter_requirement_lines(text):
        if _requirement_name(line) == package_name and _is_exact_pin(line):
            return True
    return False


def _dependency_names(items: list[str]) -> set[str]:
    return {_requirement_name(item) for item in items}


def test_runtime_dependency_sources_are_consolidated():
    requirements_in = REQUIREMENTS_IN_PATH.read_text(encoding="utf-8")
    requirements_txt = REQUIREMENTS_TXT_PATH.read_text(encoding="utf-8")
    pyproject_text = PYPROJECT_PATH.read_text(encoding="utf-8")
    pyproject = tomllib.loads(pyproject_text)
    dockerfile_text = DOCKERFILE_PATH.read_text(encoding="utf-8")

    runtime_requirement_names = _requirement_names(requirements_in)
    locked_requirement_names = _requirement_names(requirements_txt)
    dev_dependency_names = _dependency_names(pyproject["project"]["optional-dependencies"]["dev"])

    assert "fastapi" in runtime_requirement_names
    assert _has_exact_pin(requirements_in, "fastapi")
    assert all(_is_exact_pin(line) for line in _iter_requirement_lines(requirements_in))
    assert runtime_requirement_names.issubset(locked_requirement_names)
    assert 'Windows-only packages such as pywin32' in requirements_in
    assert 'python:3.11-slim' in requirements_in
    assert 'This file is autogenerated by pip-compile with Python 3.11' in requirements_txt
    assert 'pip-compile --generate-hashes' in requirements_txt
    assert 'requirements.in' in requirements_txt
    assert 'pywin32==' not in requirements_txt
    assert "dependencies" in pyproject["project"]["dynamic"]
    assert pyproject["tool"]["setuptools"]["dynamic"]["dependencies"] == {"file": ["requirements.in"]}
    assert {"pytest", "pytest-asyncio", "bandit"}.issubset(dev_dependency_names)
    assert all(_is_exact_pin(dependency) for dependency in pyproject["project"]["optional-dependencies"]["dev"])
    assert 'FROM python:3.11-slim' in dockerfile_text


def test_ci_workflows_follow_packaging_consolidation():
    backend_ci = BACKEND_CI_PATH.read_text(encoding="utf-8")
    release_workflow = RELEASE_WORKFLOW_PATH.read_text(encoding="utf-8")
    dep_review = DEP_REVIEW_WORKFLOW_PATH.read_text(encoding="utf-8")
    frontend_ci = FRONTEND_CI_PATH.read_text(encoding="utf-8")

    assert '      - "requirements.in"' in backend_ci
    assert '      - "requirements.txt"' in backend_ci
    assert '      - "pyproject.toml"' in backend_ci
    assert 'pip install .[dev]' in backend_ci
    assert 'python -m bandit -r app/ -f txt' in backend_ci

    assert 'pip install .[dev]' in release_workflow
    assert 'python -m bandit -r app/ -f txt' in release_workflow

    assert '      - "requirements.in"' in dep_review
    assert '      - "requirements.in"' in frontend_ci
    assert '      - "pyproject.toml"' in frontend_ci


def test_mobile_workspace_tooling_is_consolidated_at_root():
    mobile_manifest = json.loads(ANCAP_MOBILE_PACKAGE_PATH.read_text(encoding="utf-8"))
    root_dev_dependencies = mobile_manifest["devDependencies"]

    assert root_dev_dependencies["typescript"] == "^5.7.2"
    assert root_dev_dependencies["vitest"] == "^4.1.9"

    for manifest_path in ANCAP_MOBILE_WORKSPACE_MANIFESTS:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        dev_dependencies = manifest.get("devDependencies", {})
        assert "typescript" not in dev_dependencies, manifest_path.as_posix()
        assert "vitest" not in dev_dependencies, manifest_path.as_posix()
