from pathlib import Path


REQUIREMENTS_IN_PATH = Path("requirements.in")
REQUIREMENTS_TXT_PATH = Path("requirements.txt")
PYPROJECT_PATH = Path("pyproject.toml")
BACKEND_CI_PATH = Path(".github/workflows/backend-ci.yml")
RELEASE_WORKFLOW_PATH = Path(".github/workflows/release.yml")
DEP_REVIEW_WORKFLOW_PATH = Path(".github/workflows/dependency-review.yml")
FRONTEND_CI_PATH = Path(".github/workflows/frontend-ci.yml")
DOCKERFILE_PATH = Path("Dockerfile")


def test_runtime_dependency_sources_are_consolidated():
    requirements_in = REQUIREMENTS_IN_PATH.read_text(encoding="utf-8")
    requirements_txt = REQUIREMENTS_TXT_PATH.read_text(encoding="utf-8")
    pyproject_text = PYPROJECT_PATH.read_text(encoding="utf-8")
    dockerfile_text = DOCKERFILE_PATH.read_text(encoding="utf-8")

    assert 'fastapi==0.115.5' in requirements_in
    assert 'Windows-only packages such as pywin32' in requirements_in
    assert 'python:3.11-slim' in requirements_in
    assert 'This file is autogenerated by pip-compile with Python 3.11' in requirements_txt
    assert 'requirements.in' in requirements_txt
    assert 'pywin32==' not in requirements_txt
    assert 'dynamic = ["dependencies"]' in pyproject_text
    assert 'dependencies = { file = ["requirements.in"] }' in pyproject_text
    assert '[project.optional-dependencies]' in pyproject_text
    assert 'dev = [' in pyproject_text
    assert 'pytest==8.3.4' in pyproject_text
    assert 'pytest-asyncio==0.24.0' in pyproject_text
    assert 'bandit==1.7.10' in pyproject_text
    assert 'FROM python:3.11-slim' in dockerfile_text


def test_ci_workflows_follow_packaging_consolidation():
    backend_ci = BACKEND_CI_PATH.read_text(encoding="utf-8")
    release_workflow = RELEASE_WORKFLOW_PATH.read_text(encoding="utf-8")
    dep_review = DEP_REVIEW_WORKFLOW_PATH.read_text(encoding="utf-8")
    frontend_ci = FRONTEND_CI_PATH.read_text(encoding="utf-8")

    assert '      - "requirements.in"' in backend_ci
    assert '      - "requirements.txt"' in backend_ci
    assert '      - "pyproject.toml"' in backend_ci
    assert 'pip install .[dev]' in backend_ci
    assert 'python -m bandit -r app/ -f txt' in backend_ci

    assert 'pip install .[dev]' in release_workflow
    assert 'python -m bandit -r app/ -f txt' in release_workflow

    assert '      - "requirements.in"' in dep_review
    assert '      - "requirements.in"' in frontend_ci
    assert '      - "pyproject.toml"' in frontend_ci
