from __future__ import annotations

import argparse
import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_NAME = "EXPORT_MANIFEST.md"

EXPORT_PATHS = [
    Path("README.md"),
    Path("LICENSE"),
    Path("CONTRIBUTING.md"),
    Path("SECURITY.md"),
    Path("CODE_OF_CONDUCT.md"),
    Path("MASTER_ROADMAP.md"),
    Path("docs/STATUS_MATRIX.md"),
    Path("docs/OPEN_SOURCE_GITHUB_TRANSPARENCY.md"),
    Path("docs/ANCAP_DOCS_SPLIT.md"),
    Path("docs/VISION.md"),
    Path("docs/ARCHITECTURE_LAYERS.md"),
    Path("docs/PLAN_L0_TO_L3.md"),
    Path("docs/REPUTATION_2.md"),
    Path("docs/STAKING.md"),
    Path("docs/WHITEPAPER_PROJECT.md"),
    Path("docs/WHITEPAPER_ACP.md"),
    Path("docs/LEGAL_TERMS_TEMPLATE.md"),
    Path("docs/BRIDGE_RISK_DOCUMENTATION.md"),
    Path("docs/CONTRACT_VERIFICATION_GUIDE.md"),
    Path("docs/TESTNET_DEPLOYMENT_GUIDE.md"),
    Path("docs/AUDIT_CHECKLIST.md"),
    Path("docs/CHANGELOG_PUBLIC.md"),
]


def _validate_export_paths() -> None:
    missing = [str(path) for path in EXPORT_PATHS if not (REPO_ROOT / path).exists()]
    if missing:
        joined = ", ".join(sorted(missing))
        raise FileNotFoundError(f"missing export source files: {joined}")


def _manifest_text(exported_paths: list[Path]) -> str:
    lines = [
        "# ANCAP public docs export manifest",
        "",
        "Generated by `scripts/export_ancap_docs.py`.",
        "",
        "This bundle is the repo-staged source for the future public `ancap-docs` repository.",
        "It intentionally includes only public-safe documentation and governance files.",
        "",
        "## Exported files",
    ]
    lines.extend(f"- `{path.as_posix()}`" for path in exported_paths)
    lines.extend(
        [
            "",
            "## Excluded by design",
            "- runtime secrets (`.env`, deploy secrets, API keys, mnemonics, private keys)`",
            "- operational infrastructure (`infra/`, `deploy/`, `Sicret/`, server credentials)`",
            "- hot-wallet / bridge-signer internals and other abuse-sensitive implementation details",
        ]
    )
    return "\n".join(lines) + "\n"


def copy_export_bundle(target_dir: Path, *, clean: bool = False) -> list[Path]:
    _validate_export_paths()

    if clean and target_dir.exists():
        shutil.rmtree(target_dir)
    target_dir.mkdir(parents=True, exist_ok=True)

    exported: list[Path] = []
    for rel_path in EXPORT_PATHS:
        source = REPO_ROOT / rel_path
        destination = target_dir / rel_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
        exported.append(rel_path)

    manifest_path = target_dir / MANIFEST_NAME
    manifest_path.write_text(_manifest_text(exported), encoding="utf-8")
    return exported


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Export the public-safe ANCAP docs bundle for the future ancap-docs repo."
    )
    parser.add_argument("--target", required=True, help="Target directory for the exported docs bundle")
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Delete the target directory before exporting",
    )
    args = parser.parse_args(argv)

    target_dir = Path(args.target).resolve()
    exported = copy_export_bundle(target_dir, clean=args.clean)
    print(f"Exported {len(exported)} files to {target_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
