export type WorkflowTemplate = {
  slug: string;
  title: string;
  category: string;
  summary: string;
  description: string;
  price: { amount: string; currency: string };
  accepted_currencies: string[];
  estimated_time_minutes: number;
  preview_items: string[];
  output_items: string[];
  receipt_items: string[];
  status?: string;
  tags: string[];
  billing?: string;
  subscription_price_monthly?: { amount: string; currency: string } | null;
  subscription_price_quarterly?: { amount: string; currency: string } | null;
  subscription_price_annual?: { amount: string; currency: string } | null;
};

export type WorkflowBundle = {
  slug: string;
  title: string;
  category: string;
  summary: string;
  description: string;
  workflow_slugs: string[];
  price: { amount: string; currency: string };
  accepted_currencies: string[];
  discount_percent: number;
  estimated_time_minutes: number;
  output_items: string[];
  tags: string[];
};

export type WorkflowCreditPackage = {
  slug: string;
  title: string;
  description: string;
  price: { amount: string; currency: string };
  credit_amount: { amount: string; currency: string };
  accepted_currencies: string[];
  bonus_percent: number;
  recommended_for: string[];
};

export const fallbackWorkflowTemplates: WorkflowTemplate[] = [
  {
    slug: "token-listing-pack",
    title: "Token Listing Pack",
    category: "Launch",
    summary: "Generate reusable listing answers for exchanges, token pages, and directories.",
    description: "Creates short and long project copy, listing form answers, and exchange-friendly token descriptions.",
    price: { amount: "10", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 20,
    preview_items: ["Short project summary", "Listing answer preview", "Output structure"],
    output_items: ["Token bio", "Project description", "Listing answers", "Receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "input_hash", "status_timeline"],
    tags: ["listing", "launch", "token"],
  },
  {
    slug: "crypto-campaign-builder",
    title: "Crypto Campaign Builder",
    category: "Marketing",
    summary: "Build a launch or growth plan for Telegram, X, community actions, and referral loops.",
    description: "Creates a structured 7/14/30-day campaign plan with messaging, actions, and execution checklist.",
    price: { amount: "19", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 30,
    preview_items: ["Campaign skeleton", "Channel mix", "Execution phases"],
    output_items: ["Campaign plan", "Post ideas", "Contest mechanics", "Receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "input_hash", "proof_metadata"],
    tags: ["marketing", "growth", "campaign"],
  },
  {
    slug: "telegram-growth-kit",
    title: "Telegram Growth Kit",
    category: "Community",
    summary: "Design a Telegram operating kit with rules, posting flow, onboarding, and moderation guidance.",
    description: "Produces a practical operating pack for crypto communities that want cleaner growth and moderation structure.",
    price: { amount: "12", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 25,
    preview_items: ["Rule set preview", "Welcome flow preview", "Ops structure"],
    output_items: ["Rules", "Welcome flow", "Moderator checklist", "Receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "template_version", "completion_receipt"],
    tags: ["telegram", "community", "moderation"],
  },
  {
    slug: "airdrop-bounty-builder",
    title: "Airdrop / Bounty Builder",
    category: "Campaigns",
    summary: "Create tasks, reward logic, anti-sybil rules, and proof policy for bounty campaigns.",
    description: "Helps teams structure incentive campaigns without turning them into low-quality spam farms.",
    price: { amount: "15", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 30,
    preview_items: ["Task structure", "Reward logic", "Verification outline"],
    output_items: ["Task matrix", "Reward table", "Proof policy", "Receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "input_hash", "verification_policy"],
    tags: ["bounty", "airdrop", "campaign"],
  },
  {
    slug: "token-risk-report",
    title: "Token Risk Report",
    category: "Risk",
    summary: "Produce a structured risk and trust snapshot for a token, wallet cluster, or liquidity setup.",
    description: "Summarizes concentration, liquidity, trust signals, and operational flags into a usable risk report shell.",
    price: { amount: "14", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 20,
    preview_items: ["Risk summary", "Trust notes", "Flag categories"],
    output_items: ["Risk snapshot", "Trust signals", "Operational flags", "Receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "asset_reference", "status_timeline"],
    tags: ["risk", "token", "intelligence"],
  },
  {
    slug: "token-launch-audit-pack",
    title: "Token Launch Audit Pack",
    category: "Audit",
    summary: "Audit launch readiness across token narrative, liquidity proof, campaign plan, and trust signals.",
    description: "Produces a launch-readiness audit with scoring, gaps, mitigation tasks, and a proof-backed delivery receipt.",
    price: { amount: "79", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 55,
    preview_items: ["Launch readiness score", "Gap matrix", "Priority fixes"],
    output_items: ["Audit scorecard", "Launch risk matrix", "Fix backlog", "Proof receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "input_hash", "provider_cost_estimate", "margin_snapshot", "status_timeline"],
    tags: ["audit", "launch", "risk", "premium"],
  },
  {
    slug: "exchange-listing-submission-pack",
    title: "Exchange Listing Submission Pack",
    category: "Listings",
    summary: "Prepare exchange-facing answers, due-diligence pack, market narrative, and submission checklist.",
    description: "Creates a premium exchange listing submission pack designed for cleaner reviewer handoff and repeat submissions.",
    price: { amount: "149", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 90,
    preview_items: ["Exchange answer map", "Reviewer checklist", "Submission sequence"],
    output_items: ["Exchange form answers", "Due-diligence packet", "Reviewer memo", "Proof receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "input_hash", "listing_readiness", "margin_snapshot", "status_timeline"],
    tags: ["listing", "exchange", "launch", "premium"],
  },
  {
    slug: "kol-telegram-campaign-builder",
    title: "KOL / Telegram Campaign Builder",
    category: "Growth",
    summary: "Build KOL briefs, Telegram campaign mechanics, proof policy, and attribution-ready growth flow.",
    description: "Packages a campaign that can be handed to community operators, Telegram admins, and KOL partners without losing proof discipline.",
    price: { amount: "99", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 70,
    preview_items: ["KOL brief preview", "Telegram funnel", "Attribution plan"],
    output_items: ["KOL brief kit", "Telegram campaign plan", "Partner scripts", "Proof receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "input_hash", "campaign_attribution", "margin_snapshot", "status_timeline"],
    tags: ["kol", "telegram", "growth", "premium"],
  },
  {
    slug: "token-risk-report-pro",
    title: "Token Risk Report Pro",
    category: "Risk",
    summary: "Create a pro-grade token risk report with scoring, evidence requests, wallet/liquidity checks, and buyer-ready summary.",
    description: "Turns a lightweight token snapshot into a premium report with structured risks, evidence gaps, and recommended next checks.",
    price: { amount: "59", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 50,
    preview_items: ["Pro risk score", "Evidence gaps", "Buyer-ready summary"],
    output_items: ["Risk scorecard", "Evidence request list", "Liquidity and holder flags", "Proof receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "asset_reference", "risk_score", "margin_snapshot", "status_timeline"],
    tags: ["risk", "token", "report", "premium"],
  },
  {
    slug: "agent-api-readiness-pack",
    title: "Agent API Readiness Pack",
    category: "Developers",
    summary: "Package a crypto API or workflow for AI-agent buyers with pricing, x402 metadata, docs, and spend controls.",
    description: "Creates the commercial surface an external agent needs: endpoint offer, pricing copy, 402 response plan, curl examples, and receipt schema.",
    price: { amount: "99", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 65,
    preview_items: ["Endpoint offer map", "x402 payment shape", "Spend-control checklist"],
    output_items: ["Developer offer page", "API pricing matrix", "x402 response plan", "Proof receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "input_hash", "x402_payment_terms", "margin_snapshot", "status_timeline"],
    tags: ["api", "x402", "agents", "premium"],
  },
  {
    slug: "ai-iso-governance-readiness-pack",
    title: "AI / ISO Governance Readiness Pack",
    category: "Governance",
    summary: "Turn an AI workflow into an audit-ready operating pack with SOPs, risk controls, evidence, and corrective-action flow.",
    description: "Maps AI execution, LLM supplier controls, proof receipts, audit trails, and ISO-inspired operating discipline into a practical governance packet. This is readiness support, not a certification guarantee.",
    price: { amount: "149", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 90,
    preview_items: ["AI capability map", "ISO-style control checklist", "Evidence and audit trail plan"],
    output_items: ["AI governance memo", "SOP checklist", "Risk and control matrix", "Corrective-action plan", "Proof receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "input_hash", "ai_governance_scope", "control_evidence_map", "status_timeline"],
    tags: ["ai", "iso", "governance", "audit", "premium"],
  },
  {
    slug: "market-direction-brief",
    title: "Market Direction Brief",
    category: "Markets",
    summary: "LLM scenario analysis of near-term market direction, catalysts, and upside/downside paths.",
    description: "Educational AI scenario brief for market direction. Not investment advice.",
    price: { amount: "25", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 25,
    preview_items: ["Direction scenarios", "Catalyst map", "Invalidation levels"],
    output_items: ["Scenario brief", "Catalyst checklist", "Watchlist levels", "Receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "input_hash", "status_timeline"],
    tags: ["markets", "prediction", "ai", "analysis"],
  },
  {
    slug: "commodity-price-outlook",
    title: "Commodity Price Outlook",
    category: "Markets",
    summary: "AI outlook for oil, gas, metals, timber, uranium, and other commodities.",
    description: "Structured commodity outlook with supply/demand drivers and quote scenarios.",
    price: { amount: "29", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 30,
    preview_items: ["Supply/demand map", "Quote scenarios", "Desk risk notes"],
    output_items: ["Commodity outlook", "Driver matrix", "Scenario paths", "Receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "asset_reference", "status_timeline"],
    tags: ["commodities", "oil", "gas", "uranium", "markets", "ai"],
  },
  {
    slug: "crypto-quote-momentum-scan",
    title: "Crypto Quote Momentum Scan",
    category: "Markets",
    summary: "AI scan of crypto quote momentum and narrative heat from your inputs.",
    description: "Momentum and narrative scan with scenario weights. Not a trading signal.",
    price: { amount: "22", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 20,
    preview_items: ["Momentum framing", "Narrative heat", "Path weights"],
    output_items: ["Momentum scan", "Narrative map", "Scenario weights", "Receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "asset_reference", "status_timeline"],
    tags: ["crypto", "momentum", "quotes", "markets", "ai"],
  },
  {
    slug: "markets-ai-radar-pro",
    title: "Markets AI Radar Pro",
    category: "Markets",
    summary: "Pro multi-asset radar across crypto and commodities with AI-ranked scenarios.",
    description: "Premium cross-asset radar and monitoring checklist. Not financial advice.",
    price: { amount: "79", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 55,
    preview_items: ["Cross-asset radar", "Ranked scenarios", "Monitoring checklist"],
    output_items: ["Radar brief", "Ranked scenarios", "Contagion notes", "Evidence gaps", "Proof receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "input_hash", "margin_snapshot", "status_timeline"],
    tags: ["markets", "pro", "commodities", "crypto", "prediction", "ai"],
  },
  {
    slug: "aeterna-dna-wellness-report",
    title: "AETERNA DNA Wellness Report",
    category: "AETERNA",
    summary: "Turn a vaulted genome hash / VCF summary into an ACP-paid wellness annotation brief.",
    description: "Produces a structured genomic wellness report shell from consented DNA vault metadata. Educational and consult-prep only — not a diagnosis and not a DIY editing protocol.",
    price: { amount: "1000000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 40,
    preview_items: ["Trait annotation map", "Data-quality notes", "Partner handoff checklist"],
    output_items: ["Wellness annotation brief", "Variant summary table", "Consent receipt", "Proof receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "vault_hash_ref", "status_timeline"],
    tags: ["aeterna", "dna", "wellness", "longevity"],
  },
  {
    slug: "aeterna-longevity-panel-brief",
    title: "AETERNA Longevity Panel Brief",
    category: "AETERNA",
    summary: "Build a longevity planning brief for licensed-partner review from DNA vault + lifestyle inputs.",
    description: "Creates a longevity panel brief with risk themes, monitoring suggestions, and clinic questions. No wet-lab protocols.",
    price: { amount: "1000000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 55,
    preview_items: ["Longevity theme map", "Monitoring cadence", "Clinic question list"],
    output_items: ["Longevity brief", "Panel shortlist", "Partner referral memo", "Proof receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "input_hash", "status_timeline"],
    tags: ["aeterna", "longevity", "panel"],
  },
  {
    slug: "aeterna-pigmentation-consult-brief",
    title: "AETERNA Pigmentation Consult Brief",
    category: "AETERNA",
    summary: "Prepare a pigmentation / eye-color consult brief for licensed clinical partners.",
    description: "Structures goals, genetic context from vault metadata, and questions for a licensed consult. Does not provide CRISPR guide design or DIY enhancement steps.",
    price: { amount: "1000000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 45,
    preview_items: ["Goal framing", "Genetic context notes", "Consult agenda"],
    output_items: ["Consult brief", "Partner matching hints", "Risk/consent reminders", "Proof receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "status_timeline"],
    tags: ["aeterna", "pigmentation", "consult"],
  },
  {
    slug: "aeterna-telomere-panel-review",
    title: "AETERNA Telomere Panel Review",
    category: "AETERNA",
    summary: "Review telomere-related panel results and produce a partner-ready interpretation shell.",
    description: "Summarizes telomere panel inputs into an interpretation shell for clinician review. Not a treatment protocol.",
    price: { amount: "1000000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 35,
    preview_items: ["Panel summary", "Interpretation caveats", "Follow-up questions"],
    output_items: ["Telomere review memo", "Caveats list", "Partner handoff", "Proof receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "input_hash", "status_timeline"],
    tags: ["aeterna", "telomere", "longevity"],
  },
  {
    slug: "aeterna-disease-risk-navigator",
    title: "AETERNA Disease Risk Navigator",
    category: "AETERNA",
    summary: "Navigate disease-risk themes from consented genomic metadata into a clinician discussion guide.",
    description: "Builds a disease-risk navigator for educational discussion with licensed providers. Explicitly not diagnostic.",
    price: { amount: "1000000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 50,
    preview_items: ["Risk theme map", "Evidence gaps", "Clinician agenda"],
    output_items: ["Risk navigator", "Evidence gap list", "Referral memo", "Proof receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "vault_hash_ref", "status_timeline"],
    tags: ["aeterna", "disease-risk", "clinical"],
  },
  {
    slug: "aeterna-molecular-aging-profile",
    title: "AETERNA Molecular Aging Profile (15 axes)",
    category: "AETERNA",
    summary: "Map consented blood-RNA / PCR panel metadata onto 15 hallmark axes — configuration of aging, not one bio-age number.",
    description:
      "Partner-ready molecular aging profile across 15 hallmark themes. Educational / licensed-consult prep only — not a diagnostic PCR assay and not a DIY wet-lab kit.",
    price: { amount: "1000000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 60,
    preview_items: ["15-axis hallmark map", "Sex-aware caveats", "Partner discussion agenda"],
    output_items: [
      "Molecular aging profile brief",
      "Per-hallmark configuration table",
      "Monitoring / intervention discussion prompts",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "vault_hash_ref", "hallmark_count", "status_timeline"],
    tags: ["aeterna", "longevity", "molecular-aging", "blood-rna", "hallmarks"],
  },
  {
    slug: "aeterna-mrna-reprogramming-brief",
    title: "AETERNA Partial Reprogramming Consult (mRNA / LNP literacy)",
    category: "AETERNA",
    summary:
      "Licensed-partner consult brief on partial cellular reprogramming via mRNA in lipid nanoparticles — public patent-literacy only, 1,000,000 ACP.",
    description:
      "Discussion brief on partial epigenetic reprogramming: restore some youthful cell functions without erasing identity. Cites public USPTO notice-of-allowance journalism (Daewoong eTurna, Aug 2026). Not an approved drug. No lipid recipes, mRNA sequences, or LNP formulation steps.",
    price: { amount: "1000000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 50,
    preview_items: ["Partial vs full reprogramming framing", "Delivery literacy (mRNA in LNP)", "Partner consult agenda"],
    output_items: [
      "Partial-reprogramming consult brief",
      "Public-citation caveats (allowance ≠ grant ≠ drug approval)",
      "Licensed-partner handoff checklist",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "status_timeline"],
    tags: ["aeterna", "longevity", "mrna", "lnp", "reprogramming", "consult"],
  },
  {
    slug: "aeterna-stem-cell-organ-print",
    title: "AETERNA Stem-Cell Organ Print",
    category: "AETERNA",
    summary: "Licensed-partner organ bioprint from autologous stem cells — wisdom-tooth DPSC fallback — 250,000 ACP per organ.",
    description:
      "Settles 250,000 ACP per organ and issues a licensed-partner bioreactor handoff. Primary cell source: autologous stem cells. Fallback: dental pulp stem cells (DPSC) from a wisdom tooth. Printing occurs only in a licensed biochemical reactor operated by a verified partner. Not a home kit — no wet-lab protocol, CRISPR design, gene synthesis, or DIY cell culture.",
    price: { amount: "250000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 90,
    preview_items: ["Cell-source intake", "Bioreactor partner match", "Per-organ ACP quote"],
    output_items: ["Organ-print intake brief", "Cell-source plan", "Licensed bioreactor handoff", "Proof receipt"],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "organ_unit_price_acp", "status_timeline"],
        tags: ["aeterna", "organ-print", "stem-cells", "bioreactor"],
  },
  {
    slug: "aeterna-vet-cat-cryo-restore",
    title: "AETERNA Feline Tissue Cryoconservator-Restorer",
    category: "AETERNA",
    summary:
      "Licensed-veterinary-partner intake for a feline tissue cryoconservator-restorer (controlled-rate freeze, LN2 store, thaw/restore) — 75,000 ACP.",
    description:
      "Settles 75,000 ACP and issues a licensed-veterinary-partner brief for cat tissue banking. Conceptual architecture only. ANCAP does not manufacture the chamber, does not practice veterinary medicine, and does not claim return-to-life. No home cryo kit.",
    price: { amount: "75000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 60,
    preview_items: ["Species/tissue intake", "Veterinary partner match", "Cryo-path consent pack"],
    output_items: [
      "Feline cryo-restore intake brief",
      "Licensed veterinary handoff",
      "Non-claim checklist (no resurrection / no survival %)",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "species", "status_timeline"],
    tags: ["aeterna", "veterinary", "feline", "cryo", "tissue-bank"],
  },
  {
    slug: "aeterna-vet-regen-pod",
    title: "AETERNA Canine VET REGEN POD",
    category: "AETERNA",
    summary:
      "Licensed-veterinary-partner organ-transplant and regeneration chamber pathway for dogs (VET REGEN POD) — 180,000 ACP.",
    description:
      "Settles 180,000 ACP and issues a licensed-veterinary-partner brief for a canine organ pathway. Infographics illustrate intended partner architecture. ANCAP does not operate VET REGEN POD hardware and does not quote survival percentages. Licensed veterinarian only.",
    price: { amount: "180000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 75,
    preview_items: ["Canine organ pathway intake", "Chamber partner match", "Immunocompatibility pack"],
    output_items: [
      "VET REGEN POD intake brief",
      "Licensed veterinary handoff",
      "Non-claim checklist (no survival-rate or speed warranty)",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "species", "status_timeline"],
    tags: ["aeterna", "veterinary", "canine", "organ-print", "regen-pod"],
  },
  {
    slug: "aeterna-vinci-light-chamber",
    title: "AETERNA Vinci Light Chamber",
    category: "AETERNA",
    summary:
      "Licensed phototherapy-partner intake for a full-body LED / UVA / red / near-IR photobiomodulation chamber (Leonardo sunlight-health literacy) — 48,000 ACP.",
    description:
      "Settles 48,000 ACP and issues a licensed dermatology or phototherapy-partner brief. Inspired by Leonardo da Vinci’s notes on sunlight and the body — not a reconstructed invention. ANCAP does not manufacture the chamber and does not claim safe tanning, vitamin-D treatment, or a CE/FDA device. UV remains a known skin-cancer risk class.",
    price: { amount: "48000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 40,
    preview_items: ["Skin-type / contraindication intake", "Phototherapy partner match", "Session-protocol literacy pack"],
    output_items: [
      "Vinci light-chamber intake brief",
      "Licensed phototherapy handoff",
      "Non-claim checklist (no safe tan / no device CE-FDA claim)",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "bands", "status_timeline"],
    tags: ["aeterna", "photobiomodulation", "light-chamber", "leonardo", "consult"],
  },
  {
    slug: "aeterna-microwave-body-contouring",
    title: "AETERNA Microwave Body Contouring",
    category: "AETERNA",
    summary:
      "Licensed aesthetic/dermatology-partner intake for contact-cooled microwave body contouring (2.45 / 5.8 GHz ISM applicator) — 52,000 ACP.",
    description:
      "Settles 52,000 ACP and issues a licensed dermatology or aesthetic-medicine partner brief. Public literature discusses selective adipocyte heating with surface cooling — AETERNA does not claim blebbing, lymphatic clearance, or a guaranteed contour change. Not liposuction, not a weight-loss program, not a CE/FDA device sold by ANCAP. Licensed clinician only.",
    price: { amount: "52000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 45,
    preview_items: ["Contraindication intake", "Aesthetic partner match", "Session-protocol literacy pack"],
    output_items: [
      "Microwave body-contouring intake brief",
      "Licensed aesthetic handoff",
      "Non-claim checklist (no lipo / no guaranteed fat loss / no device CE-FDA claim)",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "bands", "status_timeline"],
    tags: ["aeterna", "body-contouring", "microwave", "aesthetic", "consult"],
  },
  {
    slug: "aeterna-biofusion-micromanipulation",
    title: "AETERNA BioFusion Micromanipulation Chamber",
    category: "AETERNA",
    summary:
      "Licensed-partner intake for a BioFusion micromanipulation chamber (IVF/ICSI, plant pollination, embryo observation, microorganism handling) — 88,000 ACP.",
    description:
      "Settles 88,000 ACP and issues a licensed-partner brief. ANCAP does not operate a fertility clinic, does not create embryos, and does not sell gene-editing or home ICSI recipes. Infographic architecture only.",
    price: { amount: "88000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 55,
    preview_items: ["Contraindication / jurisdiction intake", "ART or BSL partner match", "Non-claim protocol pack"],
    output_items: [
      "BioFusion micromanipulation intake brief",
      "Licensed lab / clinic handoff",
      "Non-claim checklist (no pregnancy / no embryo / no gene-edit / no device CE-FDA claim)",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "rails", "status_timeline"],
    tags: ["aeterna", "biofusion", "micromanipulation", "ivf", "consult"],
  },
  {
    slug: "aeterna-dpsc-biomaterial",
    title: "AETERNA Wisdom-Tooth DPSC Biomaterial",
    category: "AETERNA",
    summary:
      "Licensed-bioreactor intake to expand autologous wisdom-tooth dental pulp stem cells (DPSC) into a biomaterial construct — 65,000 ACP.",
    description:
      "Settles 65,000 ACP and issues a licensed bioreactor brief. Not a full organ print (250,000 ACP), not an FDA/CE cell therapy, not a home culture kit.",
    price: { amount: "65000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 50,
    preview_items: ["Dental / DPSC intake", "Bioreactor partner match", "Construct-goal consent pack"],
    output_items: [
      "DPSC biomaterial intake brief",
      "Licensed bioreactor handoff",
      "Non-claim checklist (not a full organ / not a cell-therapy approval)",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "cell_source", "status_timeline"],
    tags: ["aeterna", "dpsc", "wisdom-tooth", "biomaterial", "consult"],
  },
  {
    slug: "aeterna-vascular-care-plus",
    title: "AETERNA Vascular Care+",
    category: "AETERNA",
    summary:
      "Licensed phlebology/aesthetic-partner intake for Vascular Care+ (anhydrous N2+O2 flow plus light-wave applicator) — 54,000 ACP.",
    description:
      "Settles 54,000 ACP and issues a licensed clinic brief. Not a marketed medical device, not a thrombosis treatment, not a guaranteed varicose-vein claim.",
    price: { amount: "54000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 45,
    preview_items: ["Contraindication / DVT intake", "Phlebology partner match", "Session-protocol literacy pack"],
    output_items: [
      "Vascular Care+ intake brief",
      "Licensed clinic handoff",
      "Non-claim checklist (no thrombosis treatment / no guaranteed varicose cure / no device CE-FDA claim)",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "gas", "status_timeline"],
    tags: ["aeterna", "vascular", "phlebology", "gas-light", "consult"],
  },
  {
    slug: "aeterna-vascular-care",
    title: "AETERNA Vascular Care",
    category: "AETERNA",
    summary:
      "Licensed phlebology/aesthetic-partner intake for Vascular Care (ultrasound / radiofrequency / thermal applicator) — 58,000 ACP.",
    description:
      "Settles 58,000 ACP and issues a licensed clinic brief. Not surgery, not a CE/FDA device, not a guaranteed vein-diameter claim.",
    price: { amount: "58000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 45,
    preview_items: ["Contraindication intake", "Phlebology partner match", "Session-protocol literacy pack"],
    output_items: [
      "Vascular Care intake brief",
      "Licensed clinic handoff",
      "Non-claim checklist (no surgery / no guaranteed vein result / no device CE-FDA claim)",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "modalities", "status_timeline"],
    tags: ["aeterna", "vascular", "phlebology", "ultrasound", "consult"],
  },
  {
    slug: "aeterna-transdermal-pistol",
    title: "AETERNA Needle-Free Transdermal Pistol",
    category: "AETERNA",
    summary:
      "Licensed clinic-partner intake for a needle-free transdermal pistol (aerosol actives plus carrier gas) — 46,000 ACP.",
    description:
      "Settles 46,000 ACP and issues a licensed clinic brief. Not a prescription dispenser, not compounding, not a guaranteed dose or cosmetic result.",
    price: { amount: "46000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 40,
    preview_items: ["Contraindication / substance-list intake", "Clinic partner match", "Non-claim protocol pack"],
    output_items: [
      "Transdermal pistol intake brief",
      "Licensed clinic handoff",
      "Non-claim checklist (no prescription / no compounding / no guaranteed dose / no device CE-FDA claim)",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "delivery", "status_timeline"],
    tags: ["aeterna", "transdermal", "needle-free", "aesthetic", "consult"],
  },
  {
    slug: "aeterna-m-receptor-subscription",
    title: "AETERNA M-Receptor Delivery Subscription",
    category: "AETERNA",
    summary:
      "Licensed-clinic subscription for multimodal M-receptor delivery and neuromodulation literacy (patch, iontophoresis, inhaler, vagus-adjacent stimulation) — 12,000 ACP / month.",
    description:
      "Settles the first subscription period and issues a licensed-clinic partner brief. Not compounding, not a CE/FDA device, not a treatment claim.",
    price: { amount: "12000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 35,
    preview_items: [
      "Contraindication / lawful-substance intake",
      "Module match (patch / iontophoresis / inhaler / neuromodulation)",
      "Subscription period pack",
    ],
    output_items: [
      "M-receptor subscription intake brief",
      "Licensed clinic handoff",
      "Non-claim checklist (no compounding / no scopolamine recipe / no treatment claim / no device CE-FDA)",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "billing", "modules", "status_timeline"],
    tags: ["aeterna", "m-receptor", "subscription", "neuromodulation", "consult"],
    billing: "subscription",
    subscription_price_monthly: { amount: "12000", currency: "ACP" },
    subscription_price_quarterly: { amount: "32000", currency: "ACP" },
    subscription_price_annual: { amount: "108000", currency: "ACP" },
  },
  {
    slug: "aeterna-oxygen-carrier",
    title: "AETERNA Artificial Oxygen Carrier",
    category: "AETERNA",
    summary:
      "Licensed bioreactor / transfusion-medicine partner brief for hemoglobin-vesicle or perfluorocarbon-emulsion oxygen-carrier architecture literacy — 92,000 ACP.",
    description:
      "Settles 92,000 ACP and issues a licensed-partner brief. Not a blood product, not compounding of hemoglobin or PFC, not a CE/FDA oxygen therapeutic, not a manufacturing SOP.",
    price: { amount: "92000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 45,
    preview_items: [
      "Core path (hemoglobin vesicle vs PFC emulsion literacy)",
      "Licensed bioreactor partner match",
      "Non-claim protocol pack",
    ],
    output_items: [
      "Oxygen-carrier intake brief",
      "Licensed bioreactor handoff",
      "Non-claim checklist (no blood product / no hemoglobin or PFC recipe / no CE-FDA / no transfusion claim)",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "architecture", "status_timeline"],
    tags: ["aeterna", "oxygen-carrier", "hboc", "pfc", "consult"],
  },
  {
    slug: "aeterna-synthetic-blood-mamba",
    title: "AETERNA Synthetic Blood / Black Mamba Architecture",
    category: "AETERNA",
    summary:
      "Licensed bioreactor / transfusion-medicine partner brief for synthetic-blood architecture with modified Black Mamba peptide literacy — 98,000 ACP.",
    description:
      "Settles 98,000 ACP and issues a licensed-partner brief. Not a blood product, not compounding of venom peptides, hemoglobin or PFC, not a CE/FDA therapeutic, not a toxin or manufacturing SOP.",
    price: { amount: "98000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 50,
    preview_items: [
      "Layer map (core / shell / mesh / peptide literacy)",
      "Licensed bioreactor partner match",
      "Non-claim protocol pack",
    ],
    output_items: [
      "Synthetic-blood / Black Mamba architecture intake brief",
      "Licensed bioreactor handoff",
      "Non-claim checklist (no blood product / no venom or HBOC-PFC recipe / no CE-FDA / no toxin SOP)",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "architecture", "status_timeline"],
    tags: ["aeterna", "synthetic-blood", "black-mamba", "hboc", "pfc", "consult"],
  },
  {
    slug: "aeterna-adhd-support",
    title: "AETERNA ADHD / СДВГ Support Brief",
    category: "AETERNA",
    summary:
      "Licensed clinician / child psychiatry–neurology partner brief for ADHD support literacy — 42,000 ACP.",
    description:
      "Settles 42,000 ACP and issues a licensed-partner brief. Not a diagnosis, not a prescription, not stimulant compounding, not a CE/FDA drug, and not a guaranteed academic or financial outcome. Motivational literacy only.",
    price: { amount: "42000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 40,
    preview_items: [
      "Support literacy map (focus / planning / emotion / relationships)",
      "Licensed clinician partner match",
      "Non-claim protocol pack",
    ],
    output_items: [
      "ADHD / СДВГ support intake brief",
      "Licensed clinician handoff",
      "Non-claim checklist (no diagnosis / no stimulant recipe / no guaranteed billionaire path)",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "architecture", "status_timeline"],
    tags: ["aeterna", "adhd", "sdvg", "clinician", "consult"],
  },
  {
    slug: "aeterna-down-syndrome-support",
    title: "AETERNA Down Syndrome Support Brief",
    category: "AETERNA",
    summary:
      "Licensed developmental pediatrics / genetics partner brief for Down syndrome support literacy — 42,000 ACP. Not a cure.",
    description:
      "Settles 42,000 ACP and issues a licensed-partner brief. Not a cure for Down syndrome, not a diagnosis, not gene therapy or CRISPR sold by ANCAP, not a prescription, and not a guaranteed developmental outcome.",
    price: { amount: "42000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 40,
    preview_items: [
      "Support literacy map (early intervention / family / learning)",
      "Licensed clinician partner match",
      "Non-claim protocol pack",
    ],
    output_items: [
      "Down syndrome support intake brief",
      "Licensed clinician handoff",
      "Non-claim checklist (no cure / no gene therapy / no diagnosis / no outcome guarantee)",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "architecture", "status_timeline"],
    tags: ["aeterna", "down-syndrome", "trisomy-21", "clinician", "consult"],
  },
  {
    slug: "aeterna-pulmopure-subscription",
    title: "AETERNA PulmoPure Lung-Care Subscription",
    category: "AETERNA",
    summary:
      "Licensed pulmonology / respiratory clinic subscription for PulmoPure gas-vibration and lavender-oil architecture literacy — 14,000 ACP / month.",
    description:
      "Settles the first subscription period and issues a licensed-clinic partner brief. Not a CE/FDA device, not ozone therapy, not medical-gas compounding, not a guaranteed tar-clearance or clean-lungs outcome.",
    price: { amount: "14000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 35,
    preview_items: [
      "Respiratory contraindication intake",
      "Mode match (Soft / Standard / Intensive literacy)",
      "Subscription period pack",
    ],
    output_items: [
      "PulmoPure subscription intake brief",
      "Licensed pulmonology / respiratory clinic handoff",
      "Non-claim checklist (no ozone therapy / no gas compounding / no CE-FDA / no clean-lungs guarantee)",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "billing", "modules", "status_timeline"],
    tags: ["aeterna", "pulmopure", "subscription", "pulmonology", "consult"],
    billing: "subscription",
    subscription_price_monthly: { amount: "14000", currency: "ACP" },
    subscription_price_quarterly: { amount: "38000", currency: "ACP" },
    subscription_price_annual: { amount: "128000", currency: "ACP" },
  },
  {
    slug: "aeterna-barsuk-quantum-pen",
    title: "AETERNA Project Barsuk Quantum Pen Brief",
    category: "AETERNA",
    summary:
      "Licensed secure-comms partner brief for Project Barsuk pen-form cryptography, sensor, and smart-ink literacy — 36,000 ACP.",
    description:
      "Settles 36,000 ACP and issues a licensed-partner brief for a conceptual titanium pen with quantum-crypto, sensor, AI, and smart-ink literacy. Infographic ranges are fiction / architecture literacy. ANCAP is not affiliated with Parker Pen Company, does not sell a CE/FDA or military device, and does not claim unbreakable cryptography or a field weapon.",
    price: { amount: "36000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 40,
    preview_items: [
      "Secure-comms theme map",
      "Licensed partner match",
      "Non-claim protocol pack",
    ],
    output_items: [
      "Barsuk quantum-pen intake brief",
      "Licensed secure-comms handoff",
      "Non-claim checklist (no Parker claim / no weapon / no unbreakable crypto / no CE-FDA)",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "architecture", "status_timeline"],
    tags: ["aeterna", "barsuk", "quantum-pen", "secure-comms", "consult"],
  },
  {
    slug: "aeterna-teleport-earphones",
    title: "AETERNA Teleport Earphones Medevac Fiction Brief",
    category: "AETERNA",
    summary:
      "Licensed partner brief for AIRPODS T-2026 fictional medical-evacuation / quantum-comms literacy — 58,000 ACP.",
    description:
      "Settles 58,000 ACP and issues a licensed-partner brief for sci-fi teleport-earphones framed around medical evacuation and rescue literacy. Infographic ranges and combat panels are fiction. ANCAP is not affiliated with Apple, does not sell a real teleporter or military weapon system, and does not guarantee evacuation outcomes. Rescue / medevac themes only — not offensive teleport ops.",
    price: { amount: "58000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 45,
    preview_items: [
      "Medevac fiction theme map",
      "Licensed partner match",
      "Non-claim protocol pack",
    ],
    output_items: [
      "Teleport-earphones medevac intake brief",
      "Licensed partner handoff",
      "Non-claim checklist (no Apple claim / no real teleport / no weapon system / no guaranteed evac)",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "architecture", "status_timeline"],
    tags: ["aeterna", "teleport", "medevac", "fiction", "consult"],
  },
  {
    slug: "aeterna-installation-project",
    title: "AETERNA Installation Project (Neonatal Nutrition + Hyperbaric)",
    category: "AETERNA",
    summary:
      "Licensed neonatology / infant-nutrition partner brief for high-protein milk-line and neonatal hyperbaric-chamber literacy — 72,000 ACP.",
    description:
      "Settles 72,000 ACP and issues a licensed-partner brief for Installation Project milk-line and neonatal hyperbaric literacy. Not formula sold by ANCAP, not a CE/FDA device, not home HBO, not a guaranteed clinical outcome.",
    price: { amount: "72000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 50,
    preview_items: [
      "Milk-line + hyperbaric theme map",
      "Licensed partner match",
      "Non-claim / GMP literacy pack",
    ],
    output_items: [
      "Installation Project intake brief",
      "Licensed neonatology / nutrition partner handoff",
      "Non-claim checklist (no formula sale / no home HBO / no CE-FDA claim / no guaranteed outcome)",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "architecture", "status_timeline"],
    tags: ["aeterna", "installation-project", "neonatal", "infant-nutrition", "hyperbaric", "consult"],
  },
  {
    slug: "aeterna-dna-pheromone-perfume",
    title: "AETERNA DNA-Matched Pheromone Perfume (1 Bottle)",
    category: "AETERNA",
    summary:
      "Licensed cosmetic / fragrance partner fill for a DNA-vault–informed pheromone perfume — sold per bottle at 8,900 ACP.",
    description:
      "Settles 8,900 ACP for exactly one bottle and issues a licensed cosmetic / fragrance partner handoff. Optional DNA-vault content hash may inform olfactory-profile literacy; genome bytes are never uploaded. Not a drug, not an aphrodisiac claim, not a guaranteed attraction outcome, not CE/FDA pheromone medicine.",
    price: { amount: "8900", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 30,
    preview_items: [
      "Vault-hash olfactory profile literacy (optional)",
      "Pheromone fragrance blend theme map",
      "1-bottle partner fill pack",
    ],
    output_items: [
      "DNA-matched perfume bottle intake brief",
      "Licensed cosmetic / fragrance partner handoff",
      "Non-claim checklist (no drug claim / no aphrodisiac guarantee / no CE-FDA / no genome upload)",
      "Proof receipt (qty = 1 bottle)",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "intent_kind", "unit", "quantity", "architecture", "status_timeline"],
    tags: ["aeterna", "perfume", "pheromone", "dna", "cosmetic", "bottle"],
  },
  {
    slug: "counsel-jurisdiction-match",
    title: "Worldwide Legal Counsel — Jurisdiction Match",
    category: "Counsel",
    summary: "Match licensed counsel in any covered country — from 3,900 ACP.",
    description:
      "Settles ACP for a worldwide jurisdiction-match brief and licensed-counsel shortlist handoff. ANCAP is not a law firm and does not form an attorney–client relationship.",
    price: { amount: "3900", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 35,
    preview_items: ["Jurisdiction intake", "Licensed counsel shortlist", "Non-advice checklist"],
    output_items: [
      "Jurisdiction match brief",
      "Licensed counsel handoff pack",
      "Non-claim checklist",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "jurisdiction", "status_timeline"],
    tags: ["counsel", "legal", "jurisdiction", "worldwide", "handoff"],
  },
  {
    slug: "counsel-entity-setup",
    title: "Worldwide Legal Counsel — Entity / Incorporation Brief",
    category: "Counsel",
    summary: "Entity setup intake + licensed local counsel handoff — from 8,900 ACP.",
    description:
      "Settles ACP for an incorporation / entity-setup intake brief and licensed local counsel handoff. Not a ready-made company sold by ANCAP.",
    price: { amount: "8900", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 45,
    preview_items: ["Entity goals intake", "Jurisdiction options literacy", "Counsel handoff"],
    output_items: [
      "Entity setup intake brief",
      "Licensed counsel handoff",
      "Non-claim checklist",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "jurisdiction", "status_timeline"],
    tags: ["counsel", "legal", "incorporation", "entity", "worldwide"],
  },
  {
    slug: "counsel-contract-review",
    title: "Worldwide Legal Counsel — Contract Review Brief",
    category: "Counsel",
    summary: "Contract intake + licensed counsel review handoff — from 4,500 ACP.",
    description:
      "Settles ACP for a structured contract-review intake and licensed-counsel handoff. ANCAP does not redline as your attorney.",
    price: { amount: "4500", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 40,
    preview_items: ["Contract intake checklist", "Risk theme map", "Counsel handoff"],
    output_items: [
      "Contract review intake brief",
      "Licensed counsel handoff",
      "Non-claim checklist",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "status_timeline"],
    tags: ["counsel", "legal", "contract", "review", "worldwide"],
  },
  {
    slug: "counsel-crypto-assets",
    title: "Worldwide Legal Counsel — Crypto / Digital Assets Match",
    category: "Counsel",
    summary: "Crypto-assets counsel match for token / exchange / stablecoin rails — from 12,000 ACP.",
    description:
      "Settles ACP for a crypto / digital-assets literacy pack and licensed counsel match. Not an investment prospectus or securities opinion from ANCAP.",
    price: { amount: "12000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    estimated_time_minutes: 50,
    preview_items: ["Asset / activity map", "Regulatory theme literacy", "Counsel match"],
    output_items: [
      "Crypto assets counsel match brief",
      "Licensed counsel handoff",
      "Non-claim checklist",
      "Proof receipt",
    ],
    receipt_items: ["workflow_slug", "price_snapshot", "jurisdiction", "status_timeline"],
    tags: ["counsel", "legal", "crypto", "digital-assets", "worldwide"],
  },
];

export const fallbackWorkflowBundles: WorkflowBundle[] = [
  {
    slug: "launch-pack",
    title: "ANCAP Crypto Launch Pack",
    category: "Launch Suite",
    summary: "Five paid crypto launch workflows sold together as a higher-ticket execution bundle.",
    description: "Creates listing copy, launch campaign plan, Telegram operating kit, bounty structure, and token risk snapshot in one checkout.",
    workflow_slugs: [
      "token-listing-pack",
      "crypto-campaign-builder",
      "telegram-growth-kit",
      "airdrop-bounty-builder",
      "token-risk-report",
    ],
    price: { amount: "49", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    discount_percent: 30,
    estimated_time_minutes: 125,
    output_items: [
      "Listing pack",
      "Campaign plan",
      "Telegram growth kit",
      "Airdrop / bounty structure",
      "Token risk report",
      "Five proof-backed workflow receipts",
    ],
    tags: ["bundle", "launch", "growth", "risk"],
  },
  {
    slug: "growth-pack",
    title: "ANCAP Growth Pack",
    category: "Growth Suite",
    summary: "Repeatable campaign and community workflows for teams that iterate every week.",
    description: "Creates two campaign plans, two Telegram operating passes, and one bounty structure for recurring growth execution.",
    workflow_slugs: [
      "crypto-campaign-builder",
      "telegram-growth-kit",
      "airdrop-bounty-builder",
      "crypto-campaign-builder",
      "telegram-growth-kit",
    ],
    price: { amount: "59", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    discount_percent: 23,
    estimated_time_minutes: 140,
    output_items: [
      "Two campaign plans",
      "Two Telegram growth passes",
      "Bounty task matrix",
      "Five proof-backed workflow receipts",
    ],
    tags: ["bundle", "growth", "community", "campaign"],
  },
  {
    slug: "concierge-pack",
    title: "ANCAP Concierge Pack",
    category: "Concierge",
    summary: "A premium bundle for teams that want generated artifacts plus operator review.",
    description: "Creates all five launch workflows and prices the run as a concierge engagement with room for manual review and delivery polish.",
    workflow_slugs: [
      "token-listing-pack",
      "crypto-campaign-builder",
      "telegram-growth-kit",
      "airdrop-bounty-builder",
      "token-risk-report",
    ],
    price: { amount: "149", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    discount_percent: 0,
    estimated_time_minutes: 180,
    output_items: [
      "Full launch workflow set",
      "Premium review budget",
      "Custom delivery polish",
      "Five proof-backed workflow receipts",
    ],
    tags: ["bundle", "concierge", "premium", "launch"],
  },
  {
    slug: "pro-launch-pack",
    title: "ANCAP Pro Launch Pack",
    category: "Premium Launch",
    summary: "Higher-ticket launch execution pack for teams that need listing, audit, KOL, bounty, and pro risk artifacts together.",
    description: "Bundles the premium launch audit, exchange submission pack, KOL/Telegram campaign, bounty builder, and pro token risk report into one proof-backed checkout.",
    workflow_slugs: [
      "token-launch-audit-pack",
      "exchange-listing-submission-pack",
      "kol-telegram-campaign-builder",
      "airdrop-bounty-builder",
      "token-risk-report-pro",
    ],
    price: { amount: "349", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    discount_percent: 13,
    estimated_time_minutes: 295,
    output_items: [
      "Launch readiness audit",
      "Exchange listing submission pack",
      "KOL / Telegram campaign kit",
      "Airdrop / bounty structure",
      "Token Risk Report Pro",
      "Five proof-backed workflow receipts",
    ],
    tags: ["bundle", "launch", "premium", "risk", "growth"],
  },
  {
    slug: "agent-commerce-pack",
    title: "ANCAP Agent Commerce Pack",
    category: "Agent Commerce",
    summary: "A B2B pack for API owners and AI-agent builders who want pay-per-call monetization fast.",
    description: "Combines API readiness, campaign positioning, listing copy, and proof-center setup so external agents can discover, pay, and verify ANCAP-style execution.",
    workflow_slugs: [
      "agent-api-readiness-pack",
      "crypto-campaign-builder",
      "token-listing-pack",
      "token-risk-report-pro",
    ],
    price: { amount: "249", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    discount_percent: 5,
    estimated_time_minutes: 165,
    output_items: [
      "Agent/API paid endpoint offer",
      "x402-compatible payment terms",
      "Developer pricing matrix",
      "Proof-center receipt schema",
    ],
    tags: ["bundle", "api", "x402", "agents"],
  },
  {
    slug: "markets-intel-pack",
    title: "Markets Intel Pack",
    category: "Markets Suite",
    summary: "Four AI market-analysis workflows for direction, commodities, crypto momentum, and pro radar.",
    description: "Bundle for LLM-assisted market and quote-path analysis.",
    workflow_slugs: [
      "market-direction-brief",
      "commodity-price-outlook",
      "crypto-quote-momentum-scan",
      "markets-ai-radar-pro",
    ],
    price: { amount: "119", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    discount_percent: 25,
    estimated_time_minutes: 130,
    output_items: [
      "Market direction brief",
      "Commodity outlook",
      "Crypto momentum scan",
      "Markets AI radar pro",
      "Four proof-backed workflow receipts",
    ],
    tags: ["bundle", "markets", "commodities", "ai"],
  },
  {
    slug: "aeterna-longevity-pack",
    title: "AETERNA Longevity Pack",
    category: "AETERNA",
    summary: "DNA wellness + 15-axis molecular aging profile + longevity panel for ACP checkout.",
    description:
      "Three AETERNA consult-prep workflows for vaulted genomic / blood-RNA panel metadata. Licensed-partner handoff only — no DIY gene editing.",
    workflow_slugs: [
      "aeterna-dna-wellness-report",
      "aeterna-molecular-aging-profile",
      "aeterna-longevity-panel-brief",
    ],
    price: { amount: "2500000", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    discount_percent: 17,
    estimated_time_minutes: 155,
    output_items: [
      "DNA wellness report",
      "Molecular aging profile (15 axes)",
      "Longevity panel brief",
      "Three proof-backed workflow receipts",
    ],
    tags: ["bundle", "aeterna", "longevity", "dna", "molecular-aging"],
  },
];

export const fallbackWorkflowCreditPackages: WorkflowCreditPackage[] = [
  {
    slug: "starter-credits",
    title: "Starter Credits",
    description: "Enough balance to run one launch workflow or test the paid execution loop.",
    price: { amount: "25", currency: "ACP" },
    credit_amount: { amount: "25", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    bonus_percent: 0,
    recommended_for: ["first paid workflow", "proof bundle test"],
  },
  {
    slug: "launch-credits",
    title: "Launch Credits",
    description: "Best fit for the Launch Pack plus one or two follow-up reruns.",
    price: { amount: "95", currency: "ACP" },
    credit_amount: { amount: "100", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    bonus_percent: 5,
    recommended_for: ["launch pack", "campaign iteration"],
  },
  {
    slug: "growth-credits",
    title: "Growth Credits",
    description: "A larger balance for repeated launch, growth, and risk workflows.",
    price: { amount: "225", currency: "ACP" },
    credit_amount: { amount: "250", currency: "ACP" },
    accepted_currencies: ["ACP", "wACP"],
    bonus_percent: 11,
    recommended_for: ["teams", "multiple assets", "repeat campaigns"],
  },
];

export function getFallbackWorkflowTemplate(slug: string): WorkflowTemplate | null {
  return fallbackWorkflowTemplates.find((item) => item.slug === slug) || null;
}

export function getFallbackWorkflowBundle(slug: string): WorkflowBundle | null {
  return fallbackWorkflowBundles.find((item) => item.slug === slug) || null;
}

export function getFallbackWorkflowCreditPackage(slug: string): WorkflowCreditPackage | null {
  return fallbackWorkflowCreditPackages.find((item) => item.slug === slug) || null;
}
